### ISSUE TITLE
New colors don't appear

### ISSUE THREAD

**Issue by enboig** [ndunand/moodle-atto_morefontcolors#1]
After installing the pluguin and configurint the toolbar I added one color but it is not listed in the toolbar.
My value for "atto_morefontcolors | availablecolors" is:
#EF4540
#FFCF35
#98CA3E
#7D9FD3
#333333
#800080
#FFFFFF

I tried purging caches in moodle and in browser.

**Comment by ndunand** [comment]
Hi,
Could you please copy-paste your value for the "`editor_atto | toolbar`" configuration setting?
Here's mine below, for instance:

    collapse = collapse
    style1 = title, bold, italic, morefontcolors
    list = unorderedlist, orderedlist
    links = link
    files = image, imagedragdrop, media, managefiles, poodll
    hr = hr
    style2 = underline, strike, subscript, superscript
    align = align
    indent = indent
    insert = equation, charmap, table, clear
    undo = undo
    accessibility = accessibilitychecker, accessibilityhelper
    other = html, fullscreen
    corr = corrections

**Comment by enboig** [comment]
You are right, I was using "fontcolor" where I should have used "morefontcolors". Now it works perfectly.

Thanks

**Comment by ndunand** [comment]
Great, thanks for reporting back.
