### ISSUE TITLE
Custom font color button doesn't work everytime

### ISSUE THREAD

**Issue by pingtaoye** [ndunand/moodle-atto_morefontcolors#13]
We are experiencing an issue that the custom font color picker button does not work when you type something in the text area at the first time. I have to save the text then the color panel will display normally. And when it happens, if I enter a color hex code or an RBG code in the box, it always sets to red.
![morefontcolor](https://user-images.githubusercontent.com/17863517/31401501-e6017816-ada7-11e7-97f9-2e11b7dd9836.jpg)
![more font colours](https://user-images.githubusercontent.com/17863517/31401505-e7fce092-ada7-11e7-9b6f-bdfe18246390.jpg)

**Comment by ndunand** [comment]
Hi @pingtaoye sorry for leaving this unanswered for so long.

I can't reproduce this. Can you please provide steps as to how to yield this result? Also, browser type and version would help.
