### ISSUE TITLE
Plugin not working in Moodle 3.8

### ISSUE THREAD

**Issue by steveradford** [ndunand/moodle-atto_morefontcolors#16]
I'm aware that the current version of the plugin is only showing as approved up to V3.7, however Nicolas has asked me to add a bug for V3.8.

When installed in V3.8 only the standard colours display in Atto:

Server Environment
![image](https://user-images.githubusercontent.com/64131408/80714316-ae55e080-8aec-11ea-8e04-44fee3af1fa3.png)
 
 
Plugin Version
![image](https://user-images.githubusercontent.com/64131408/80714355-bb72cf80-8aec-11ea-863b-2402bd85a995.png)
 
 
Atto Performance
![image](https://user-images.githubusercontent.com/64131408/80714392-c9285500-8aec-11ea-88bf-f5f2bd9f7efd.png)

**Comment by ndunand** [comment]
Hi @steveradford thanks for taking the time to report here. A few leads:
- are you sure the plugin is enable in the atto palette (i.e. we're not looking at the standard 'atto_fontcolor' plugin)?
- what theme are you using?
- whare are the atto_modefontcolors specific settings?

**Comment by steveradford** [comment]
> * are you sure the plugin is enable in the atto palette (i.e. we're not looking at the standard 'atto_fontcolor' plugin)?

You are correct, this was the issue, I have corrected that and the plugin is now working correctly. (For info, that was the case prior to upgrading, but the process of upgrading from V3.6 to V3.8 seems to have reset the Atto toolbar to default settings).

**Comment by ndunand** [comment]
Thanks @ndunand , marking the plugin as working for Moodle 3.8 then.
