### ISSUE TITLE
Plugin-Zip Root Filename

### ISSUE THREAD

**Issue by Menrath** [ndunand/moodle-atto_morefontcolors#22]
Please change the name of the root directory within the zip release file to just morefontcolors, as all other plugins do.

This breaks (maybe not only) our automizations. Thank you! :)

**Comment by ndunand** [comment]
Hi,
There is no root directory here on this plugin, but GitHub makes it so that when downloading the whole code is wrapped in a directory bearing the name of the repository. This is not something that I can modify.
