### ISSUE TITLE
Discrepancy in yui/src/button/js/button.js

### ISSUE THREAD

**Issue by jinhofer** [ndunand/moodle-atto_morefontcolors#4]
The -debug.js file contains (78-90):
}, {
    ATTRS: {
        /**
         * The list of available colors
         *
         * @attribute colors
         * @type array
         * @default {}
         */
        colors: {
            value: {}
        }
    }
Whereas the src code does NOT contain that bit. Performing a build step (shifter) on the src will cause the plugin to break. Could you make this fix?

**Comment by ndunand** [comment]
I re-ran the shifter, so this is now fixed.
