### ISSUE TITLE
Default Color Red (Minor-Negligible)

### ISSUE THREAD

**Issue by samberg0001** [ndunand/moodle-atto_morefontcolors#8]
When the user highlights text and activates the More Font Colors (MFC) button,
the default value in the MFC window is red (rgb = (255,0,0) by default), so when it's submitted, all the highlighted text turns red.

If user decides they don't want to change the color and click "submit" their text changes color instead of remaining unchanged, which is different behavior than, say, Microsoft Word.

**Comment by ndunand** [comment]
Thanks for reporting this. I consider it as a non-issue as the user could simply cancel to get out without modification.
