### ISSUE TITLE
Dropdown menu width too small, with Adaptable theme

### ISSUE THREAD

**Issue by matcho** [ndunand/moodle-atto_morefontcolors#9]
When used with adaptable theme, the dropdown menu is broken and the color squares are hidden.
The CSS rule responsible for that is:
`.atto_fontcolor_button .dropdown-menu {
    min-width: inherit;
}`
Manually setting a min-width of 50px fixes it :
`.atto_fontcolor_button .dropdown-menu {
    min-width: 50px;
}`
An bug was filed to Adaptable theme maintainers : https://bitbucket.org/covuni/moodle-theme_adaptable/issues/385/atto-plugins-dropdown-menus-broken

Greetings from Montpellier,
Mathias

**Comment by ndunand** [comment]
Salut Mathias,

Thanks for the report. Does your fix also work when there are several columns in the palette, as in the attached screenshot?

<img width="227" alt="screen shot 2016-03-09 at 07 19 30" src="https://cloud.githubusercontent.com/assets/762972/13627023/6f611904-e5c7-11e5-8679-5eebd2e0ec35.png">

**Comment by matcho** [comment]
Salut Nicolas,

Mhh clearly it doesn't, I didn't think about it at all :)
The fact is, maybe another bug misled me : although my "Available colors" setting contains the 16 default colors, and I checked "Allow custom color", the picker only shows 6 colors on 1 column : white, red, yellow, green, blue, black.
If I increase the container width, there's only white space in it and no custom color picker.
What did I do wrong ? I installed the plugin from a zip archive via moodle.org plugins catalog. Maybe I don't have the right version ? Note that the exact same problem happens with "atto_morebackcolors" plugin, that claims to be forked from "atto_morefontcolors".

Thanks,
Mathias

**Comment by matcho** [comment]
Hi,

Forget the comment I just delete, I was totally out. I was mixing "fontcolor" and "morefontcolor" because the display bug affects both. Maybe I should file the bug to Atto maintainers, then ?

Anyway you're right, the fix doesn't work for the default palette. Setting min-width to "initial", "0" or any other value I tried doesn't work. Setting it to an invalid value makes it work, I don't know what should be the right value for "min-width" in such a case.
```css
.atto_morefontcolor_button .dropdown-menu {
  min-width: foo;
}
```
Greetings,
Mathias

**Comment by ndunand** [comment]
Hi,

OK, thanks. What if you just remove the `min-width` property? Invalid CSS values should just be ignored, so removing it should achieve the same result.

**Comment by matcho** [comment]
Removing the "min-with" property in morefontcolors/styles.css works. And it doesn't break the rendering with the default "Clean" theme. I guess it's the best way to fix the issue, although I'm puzzled by the fact that the default atto color picker (fontcolor) also suffers from the bug... I'll ask again to "Adaptable" theme maintainers if they can do anything at their level.

**Comment by ndunand** [comment]
Closing this as it looks old now. Feel free to reopen is you consider this should stil be solved.
